CREATE DATABASE `projectox`;

USE `projectox`;

/*Table structure for table `customer` */

DROP TABLE IF EXISTS `customer`;

CREATE TABLE `customer` (
  `CUST_ID` INT(8) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'Customer''s UID',
  `FNAME` TINYTEXT NOT NULL COMMENT 'Customer''s First Name',
  `LNAME` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT 'Customer''s Last Name',
  `PHONE` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT 'Customer''s Contact',
  `ADDRESS` TEXT,
  PRIMARY KEY (`CUST_ID`)
) ENGINE=INNODB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `login` */

DROP TABLE IF EXISTS `login`;

CREATE TABLE `login` (
  `CUST_ID` INT(8) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `EMAIL` TINYTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `PWORD` TINYTEXT NOT NULL,
  `VERIFY_CODE` TEXT,
  `VERIFIED_AT` TEXT,
  `ACC_TYPE` TEXT NOT NULL,
  PRIMARY KEY (`CUST_ID`),
  CONSTRAINT `login_ibfk_1` FOREIGN KEY (`CUST_ID`) REFERENCES `customer` (`CUST_ID`)
) ENGINE=INNODB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `order` */

DROP TABLE IF EXISTS `order`;

CREATE TABLE `order` (
  `ORDER_ID` INT(8) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `CUST_ID` INT UNSIGNED NOT NULL,
  `ORD_DATE` DATE NOT NULL,
  `TOTAL` DECIMAL(11,0) DEFAULT NULL,
  `STATUS` TINYTEXT NOT NULL,
  PRIMARY KEY (`ORDER_ID`),
  KEY `CUST_ID` (`CUST_ID`),
  CONSTRAINT `order_ibfk_1` FOREIGN KEY (`CUST_ID`) REFERENCES `customer` (`CUST_ID`)
) ENGINE=INNODB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `pass_reset` */

DROP TABLE IF EXISTS `pass_reset`;

CREATE TABLE `pass_reset` (
  `PASS_RESET_ID` INT NOT NULL AUTO_INCREMENT,
  `PASS_RESET_TOKEN` TEXT NOT NULL,
  `PASS_RESET_EXPIRES` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`PASS_RESET_ID`)
) ENGINE=INNODB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `prod_order` */

DROP TABLE IF EXISTS `prod_order`;

CREATE TABLE `prod_order` (
  `PROD_ORDER_ID` INT(8) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `ORDER_ID` INT UNSIGNED NOT NULL,
  `PROD_ID` INT UNSIGNED NOT NULL,
  `SPECS_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`PROD_ORDER_ID`),
  KEY `ORDER_ID` (`ORDER_ID`),
  KEY `PROD_ID` (`PROD_ID`),
  KEY `SPECS_ID` (`SPECS_ID`),
  CONSTRAINT `prod_order_ibfk_1` FOREIGN KEY (`ORDER_ID`) REFERENCES `order` (`ORDER_ID`),
  CONSTRAINT `prod_order_ibfk_2` FOREIGN KEY (`PROD_ID`) REFERENCES `product` (`PROD_ID`),
  CONSTRAINT `prod_order_ibfk_3` FOREIGN KEY (`SPECS_ID`) REFERENCES `specs` (`SPECS_ID`)
) ENGINE=INNODB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `product` */

DROP TABLE IF EXISTS `product`;

CREATE TABLE `product` (
  `PROD_ID` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `PRICE` DECIMAL(10,0) UNSIGNED NOT NULL,
  PRIMARY KEY (`PROD_ID`)
) ENGINE=INNODB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Table structure for table `specs` */

DROP TABLE IF EXISTS `specs`;

CREATE TABLE `specs` (
  `SPECS_ID` INT(8) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `FURNI_TYPE` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `SPECIES` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `LIVE_EDGE` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `BASE_STYLES` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `EPOXY_OPTION` TEXT,
  `EPOXY_STYLE` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `EPOXY_TYPE` TEXT,
  `EPOXY_COLOR` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `ADD_DETAILS` TEXT,
  PRIMARY KEY (`SPECS_ID`)
) ENGINE=INNODB AUTO_INCREMENT=48 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
